// Quick test harness — runs the parser against the trainer's PDF text content.
// Usage: node scripts/test-parser.mjs
import { parseTrainingPlan } from '../src/lib/parseTrainingPlan.ts';

const sampleText = String.raw`
MATT LUXFORD
ALL SETS LISTED ARE WORKING SETS - USE 1-2 FEEDER SETS WHEN REQUIRED
TRAIN CALVES EVERY OTHER TRAINING DAY - 6-8 WORKING SETS
ABS & PRACTICE CORE CONTROL AND VACUUM FASTED DAILY
TAKE REST DAYS AS AND WHEN REQUIRED
REST PERIODS CAN VARY DEPENDING ON HOW TAXING MOVEMENT IS
PUSH
BODY PART EXERCISE TOTAL SETS REP RANGE TEMPO NOTES
CHEST PRIME PEC DECK FLY 3 10-12 1 1 3 2 Slow tempo 3-1-3-1 (Beginning-mid range)
CHEST ATLANTIS FLAT CHEST PRESS 2 8-10 1 0 1 0 SEMI NEUTRAL GRIP
CHEST NAUTILUS INCLINE CHEST PRESS 3 8-10 1 0 2 0 SLOWER NEGATIVE THAN ABOVE
SHOULDERS PANATTA LATERAL RAISE STANDING 3 12-15 1 1 1 0
Optional intensifier for set 3: Go to dumbbells 2.5kg x 50, 7.5kg x 25, 12.5kg x 12, 17.5kg x 6, 12.5kg x 12, 7.5kg x 25
2.5kg x 50, 1 minute hold with arm out to side. 3 forced negatives (partner)
SHOULDERS PLATE LOADED SHOULDER PRESS OF CHOICE 3 6-10 1 0 2 0
TRICEPS STANDING OVERHEAD VULKEN GRIP EXTENSION 3 15-20 1 1 2 1 Set 3: 50 reps, drop, 30 reps, drop, 20 reps. Go back up to what you got 50 reps of for 10 reps.
TRICEPS PRIME DIPS MACHINE 3 10-12 1 0 2 0
CALVES WORKOUT
SMITH MACHINE REST PAUSE 100 reps, increase weight, 75 reps, increase weight 50 reps
Seated Calf raise 3 sets with 30 second weighted stretch after each
PULL
BODY PART EXERCISE TOTAL SETS REP RANGE TEMPO NOTES
BACK PRIME SINGLE ARM HIGH TO LOW PULLDOWN 3 8-10 1 1 2 1 LOWER LAT BIAS
BACK ASSISTED PULLUPS 6 10 3 1 3 1 45 SECONDS MAX REST SLOW TEMPO
BACK PRIME CHEST SUPPORTED ROW MACHINE 3 8-10 1 0 1 0 MID BACK/TRAP FOCUS
1 X 8-10 REPS / 1 12-15 REPS BACK OFF
BACK DEADLIFT FROM FLOOR 2 6-8 1 1 1 1 1 X 6-8 REPS / 1 8-10 REPS BACK OFF
BACK SINGLE ARM UNDERHAND ROW MACHINE HAMMER STRENGTH 2 8-10 1 1 3 0 LOWER LAT BIAS
BICEPS EZ BAR CURL 3 10-12 1 0 1 0 DROPSET SUPERSET WITH REVERSE GRIP
REAR DELTS REVERSE PEC DECK PRIME 3 10-12 1 0 1 0
ABS WORKOUT
LEGS
BODY PART EXERCISE TOTAL SETS REP RANGE TEMPO NOTES
GLUTES/HAMS PRIME ADDUCTOR 3 8-10 1 1 2 0 10 SETS 10 REPS 10 SECOND REST
GLUTES/HAMS SEATED LEG CURL 2 8-10 1 1 2 1
GLUTES/HAMS LEG EXTENSIONS 2 8-10 1 1 2 1
QUADS CYBEX SQUAT PRESS 2 8-10 4 1 1 0 EXTREMELY SLOW NEGATIVE AND FULL ROM
QUADS SQUAT VARIATION OF CHOICE 2 10-12 1 0 1 0 1 X 8-10 REPS / 1 10-12 REPS BACK OFF
GLUTES/HAMS GRANITE WEIGHTED HYPEREXTENSION 2 8-10 1 1 2 0
UPPER
BODY PART EXERCISE TOTAL SETS REP RANGE TEMPO NOTES
SHOULDERS SMITH MACHINE SHOULDER PRESS 2 8-10 1 0 1 0 1 X 8-10 REPS / 1 12-15 REPS BACK OFF
CHEST INCLINE CABLE FLY 2 8-10 3 1 3 1 STRETCHED RANGE HOLD
CHEST NAUTILUS FLAT PRESS 2 10-12 1 1 2 1 LAST SET DOUBLE DROP SET
BACK NARROW GRIP LAT PULLDOWN 2 8-10 1 1 2 0
BACK PANATTA T BAR ROW 2 8-10 1 1 2 0 ELBOWS FLARED
SHOULDERS DB REVERSE FLY 2 8-10 1 0 1 0 HEAVY
TRICEPS ROPE PUSHDOWN 3 8-10 1 1 2 1 SET 3: MUSCLE ROUND
BICEPS UNILATERAL PREACHER CURL 3 8-10 1 1 3 1 5 SECONDS FORCED
ABS WORKOUT
ARMS
BODY PART EXERCISE TOTAL SETS REP RANGE TEMPO NOTES
TRICEPS JM PRESS 3 10-12 1 0 1 0 LAST SET DOUBLE DROP SET
TRICEPS OVERHEAD TRICEPS MACHINE 3 8-10 1 0 2 1 SEMI PRONATED GRIP
TRICEPS CROSS BODY EXTENSIONS 3 8-10 1 0 1 0
TRICEPS LONG ROPE EXTENSIONS 3 Max Reps 1 0 1 0 FEET ELEVATED
BICEPS STRAIGHT BAR CABLE CURL 3 10-12 1 1 1 0
BICEPS ROPE HAMMER CURL 3 10-12 1 1 1 0
BICEPS DUAL D HANDLE CABLE DRAG CURL 3 8-10 1 1 2 0
BICEPS PREACHER CURL 3 8-10 2 1 3 1 PAINFULLY SLOW CONTROL
Abdominals 2x Per Week
BODY PART EXERCISE TOTAL SETS REP RANGE TEMPO NOTES
ABDOMINALS WEIGHTED ABS MACHINE OF CHOICE 3 8-10 1 1 2 0
ABDOMINALS DECLINE SIT UPS WEIGHTED 3 6-8 2 1 3 1
ABDOMINALS HYPEREXTENSION SIDE CRUNCHES 2 10-12 1 1 1 1 2 sets each side
ABDOMINALS EXERCISE BALL PULL INS 3 Max reps 1 1 2 1
ABDOMINALS LYING LEG RAISE WITH CRUNCH 3 Max reps 1 0 1 0
ABDOMINALS PLANK 1 Max Hold N/A 3 second hold each side
`;

const result = parseTrainingPlan(sampleText);
console.log(JSON.stringify(result, null, 2));
console.log('\n=== SUMMARY ===');
console.log(`Days: ${result.days.length}`);
for (const d of result.days) {
  console.log(`  ${d.name}: ${d.exercises.length} exercises, ${d.inlineNotes.length} inline notes`);
}
console.log(`Warnings: ${result.warnings.length}`);
console.log(`Unparsed lines: ${result.unparsedLines.length}`);
if (result.unparsedLines.length) {
  console.log('\n--- Unparsed lines ---');
  for (const u of result.unparsedLines) console.log(' • ' + u);
}
